version: "3.8"

services:
  # Development container. Runs in debug mode and live-reloading on every source file update.
  develop:
    hostname: goPush-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      DEBUG: "true"
      SERVING_PORT: ":8009"
    cap_add:
      - SYS_PTRACE
    volumes:
      - .:/goPush
    working_dir: /goPush
    ports:
      - "8009:8009"  # Opened ports
      - "40000:40000"  # Opened ports
    links:
      - goPush-data
    command: bash -c "go mod download && make serve"

  goPush-data:
    image: mongo:4.4
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=goPush
    volumes:
      - ./.data/db:/data/db
    command: mongod --logpath=/dev/null # --quiet
