# настройки непосредственно goPush
goPush:
  name: "Push Notifications server"
  version: "0.0.1.0b"
  host:
  port: 8009
  # этот ключ goPush будет ждать в Header Rest-запроса
  apikey: "123"
  # максимальное кол-во токенов на один тип устройства пользователя
  # если кол-во будет превышено, то самый старый токен будет удален
  # пока НЕ ИСПОЛЬЗУЕТСЯ
  maxTokenNumber: 2

# Authorization ключ для FCM
fcmServerKey: "AAAAV0Tez..."
  
# место хранения данных по пользователям и токенам их девайсов
mongo:
  uri: "mongodb://goPush-data:27017"
  name: "gopush"